# Generated by Django 5.1.4 on 2025-01-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.CharField(max_length=1000)),
                ('Ticket_id', models.CharField(max_length=1000)),
                ('Ticket_type', models.CharField(max_length=20)),
            ],
        ),
    ]
