# Generated by Django 5.1.4 on 2025-01-22 12:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_ticketbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketbooking',
            name='id',
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='Ticket_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
