# Generated by Django 5.1.4 on 2025-01-27 09:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_remove_ticketbooking_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('User_id', models.CharField(max_length=1000)),
                ('Reservation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Room_type', models.CharField(max_length=20)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
            ],
        ),
    ]
